set -g mode-keys vi
set -g status-keys vi
set -s set-clipboard off
bind-key -T copy-mode-vi y send -X copy-pipe 'xsel -ib'

# List of plugins
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# source -> prefix+I to install
# prefix+P to toggle logging
# prefix+alt+P to capture retrospectively
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'

# Initialize TMUX plugin manager (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'

